###########################################################################################
# This is a YML file. Be careful when editing. Check your edits in a YAML checker like    #
# the one at http://yaml-online-parser.appspot.com                                        #
###########################################################################################
# This is a configuration file for SkyBlock core.
# For other configurations, please take a look in the plugin folder for:
# - worlds.yml | schematics/configuration.yml | challenges.yml
---

## Do not change this
version: "MicroGitHub"

## Game Prefix.
Prefix: "&d[&eASkyBlock&d] &e"
## Allow debugging
debug: true
## Allow to get Updates from GitHub database
allowUpdate: false
## Locale language
##  Locale is CASE_SENSITIVE!
##  Available locales are:
##    en_US - English by larryTheCoder.
##    de_DE - German by UnexMC
defaultlanguage: "en_US"
# Team chatting
teamChat: true
# Enable FastLoad. This usually task the plugin to load
# 100ms after plugin load. Good but bad looking in console
fastLoad: false
# Fast cache
# Enable to enable fast cache
# Not every data are saved efficiently
# Bugs are rarely found on this (But recommended to NOT using it)
fastCache: false

## Economy section
economy:
  # Enable economys?
  # You can set this to 'true' if you has an Economy plugin listed below
  # If there is no economy plugin detected, this section will return 'false'
  #  Supported economy are:
  #  - EconomyAPI
  enable: false
  # Starting island money
  #  Decide if you want the first island created to be paid or not
  payNewIsland: false
  # Island cost $$$
  #  You will NOT have to put '$' symbol
  islandCost: 10

##### Island Related Settings #####
island:
   # Island name limit
   #   Here you can control th
   #   Limit of the island naming size
   #   You can use -1 to make it infinite
   nameLimit: 20
   # Island reset
   #   Here you can control the 
   #   Blocks when players reset their island
   #   NOTE: more higher you made, more lag your server
   #         depends on your schematic blocks
   chunkResetPerBlocks: 256
   # This feature intended in seconds
   # Not in minute
   # (Unavailable)
   deleteTiming: 180
   # Restricted commands in Island / SkyBlock
   #   level. You must respect the command format
   #   Such as `/example1, /example2`
   # (Unavailable)
   restrictedCommands: "/exampleCommand, /exampleCommand2"
   # Island reset
   # You can use -1 for unlimited island reset
   # (Unavailable)
   reset: 3
   # Island gameMode, you can decide this
   gamemode: 0
   # Island addMember time out
   #   You can use -1 for unlimited time but 
   #   Recommended 20 seconds
   timeOut: 20
   # Island companion names
   #   Your passion to add this or nor
   #   Syntax: "&aFood?, &eEmergency Food?, &cYour Pet!"
   #  (Unavailable)
   companionNames: "&aFood?, &eEmergency Food?, &cYour Pet!"
   # Items section
   items:
     # Items that will be in the chest when the player starts an island
     # Must be in Nukkit Item format. Format is <ID>:<Qty> or <ID>:<Data>:<Qty>
     # Use <Data> to set the durability of a item or to select sub-items/colors.  
     #
     # To use this, please set `USE_CONFIG_CHEST` to true on the schematic
     # configuration to use this properly.
     #
     # Check console for errors and guidance after reloading configuration
     chestItems: 'ICE:2 MELON:1 TORCH:2 BONE:1 325:1:10 PUMPKIN_SEEDS:1 SUGAR_CANE:1 RED_MUSHROOM:1 BROWN_MUSHROOM:1 CACTUS:1 BREAD:1 WHEAT:1 LEATHER_BOOTS:1 LEATHER_HELMET:1 LEATHER_CHESTPLATE:1 LEATHER_LEGGINGS:1'
  
# Protection settings
# Some features may be unavailable
protection:
   # Protection Setting Flags:
   # ACID_DAMAGE, ANVIL, BEACON, BED, BREAK_BLOCKS, BREEDING, BREWING, 
   # BUCKET, COLLECT_LAVA, COLLECT_WATER, CHEST, CHORUS_FRUIT, CRAFTING, CROP_TRAMPLE, 
   # DOOR, EGGS, ENCHANTING, ENDER_PEARL, ENTER_EXIT_MESSAGES, FIRE, FIRE_EXTINGUISH, 
   # FIRE_SPREAD, FURNACE, GATE, HORSE_INVENTORY, HORSE_RIDING, HURT_MOBS, LEASH,
   # LEVER_BUTTON, MOB_SPAWN, PLACE_BLOCKS, PORTAL, PRESSURE_PLATE, PVP,
   # MILKING, NETHER_PVP, REDSTONE, SPAWN_EGGS, SHEARING, VILLAGER_TRADING,
   # VISITOR_ITEM_DROP, VISITOR_ITEM_PICKUP
   #
   # -- World defaults --
   # Applies everywhere and are the default for islands and spawn.
   # If not listed, default is false.
   world:
     # Acid causes damage above sea-level (if acid is active)
     ACID_DAMAGE: true
     # Allow anvil use
     ANVIL: false
     # Allow beacon use
     BEACON: false
     # Allow bed use
     BED: false
     # Players can break blocks or generally damage things
     BREAK_BLOCKS: false
     # Allow animal breeding
     BREEDING: false
     # Allow use of cauldrons and brewing stands
     BREWING: false
     # Allow use of buckets, either fill or dump them
     BUCKET: false
     # Collect Lava (overrides BUCKET setting for collecting lava)
     COLLECT_LAVA: false
     # Collect water (overrides BUCKET setting for collecting water)
     COLLECT_WATER: false
     # Allow access chests of any kind, droppers, dispensers and hoppers
     CHEST: false
     # Allow eating or use of chorus fruit
     CHORUS_FRUIT: false
     # Allow use of crafting benches
     CRAFTING: true
     # Allow creepers to hurt players (but not damage blocks)
     CREEPER_PAIN: true
     # Allow crop trampling
     CROP_TRAMPLE: false
     # Allow use of doors or trapdoors. Not including redstone activations.
     DOOR: true
     # Allow chicken egg throwing
     EGGS: false
     # Allow use of enchanting tables
     ENCHANTING: true
     # Allow enderpearl throwing
     ENDER_PEARL: false
     # Enable or disable join/leave messages from the player's island
     ENTER_EXIT_MESSAGES: true
     # Allow fire (flint & steel use, TNT priming) Making portals is allowed.
     FIRE: false
     # Can extinguish fires by punching them
     FIRE_EXTINGUISH: false
     # Allow fire spreading
     FIRE_SPREAD: false
     # Allow furnace use
     FURNACE: true
     # Allow gate use
     GATE: false
     # Allow horse/llama inventory use - only works when riding is enabled     
     HORSE_INVENTORY: false
     # Allow riding of horses/llamas
     HORSE_RIDING: false
     # Allow friendly mob hurting(cows etc.)
     HURT_MOBS: false
     # Allow monsters hurting
     HURT_MONSTERS: true
     # Allow leash use
     LEASH: false
     # Allow lever or button use
     LEVER_BUTTON: true
     # Cows can be milked
     MILKING: true
     # Animals, etc. can spawn naturally
     MOB_SPAWN: true
     # Allow monsters to spawn naturally
     MONSTER_SPAWN: true
     # Allow PVP in the nether world
     NETHER_PVP: false
     # Players can place blocks
     PLACE_BLOCKS: false
     # Allow portal use
     PORTAL: true
     # Allow pressure plate activation by players
     PRESSURE_PLATE: true
     # Allow PVP in the overworld
     PVP: false
     # Allow adjustment of diodes or comparators
     REDSTONE: false
     # Spawn eggs can be used
     SPAWN_EGGS: false
     # Allow sheep shearing
     SHEARING: false
     # Allow trading with villagers
     VILLAGER_TRADING: true
     # Allow item drop
     VISITOR_ITEM_DROP: true
     # Allow item pickup
     VISITOR_ITEM_PICKUP: true
   # -- Island Settings --
   # Settings for islands. Some are for visitors, some for the island itself.
   # If setting is not listed, it will not show in GUI and the world default will be used.
   # Add settings here to give the player the ability to see them in the GUI. Give the
   # player the permission for the setting for them to be able to change the setting.
   island:
     # Allow visitor anvil use
     ANVIL: true
     # Allow visitor beacon use
     BEACON: false
     # Allow visitor bed use
     BED: false
     # Allow visitor block breaking, or other damage
     BREAK_BLOCKS: false
     # Allow visitor animal breeding
     BREEDING: false
     # Allow visitor use of cauldrons and brewing stands
     BREWING: false
     # Allow visitor access chests of any kind, droppers, dispensers and hoppers
     CHEST: false
     # Allow visitors to use crafting benches
     CRAFTING: true
     # Allow visitor use of doors or trapdoors. Not including redstone activations.
     DOOR: true
     # Allow visitor chicken egg throwing
     EGGS: false
     # Allow visitors to use enchanting tables
     ENCHANTING: true
     # Allow visitor furnace use
     FURNACE: true
     # Allow gate use
     GATE: true
     # Allow portal use by visitors
     PORTAL: true
     # Allow pressure plate activation by visitors (players only)
     PRESSURE_PLATE: false
     # Allow adjustment of diodes or comparators
     REDSTONE: false
     # Allow visitors to shear sheep
     SHEARING: false
   
# General section
general:
  # The time for teleports 
  # Must be in integer
  # Put 0 if you dont want to enable this
  islandTeleportDelay: 2
  # Teleport cancel distance
  # How far players can go to cancel
  # Teleports
  teleportCancelDistance: 0.2
  # Broadcast 1st time challenge completion messages to all players.
  # Change to false if the spam becomes too much.
  broadcastmessages: true
  
## Database
# Recommended to NOT change this in mid game
database:
  # Configuration of DATABASE Connection:
  #  DBLIB  - default connection, defined in DbLib plugin
  #  SQLITE - custom sqlite file
  #  MYSQL  - custom MySql configuration
  connection: sqlite
  SQLite:
    # SQlite file name.
    # You can pick your name and
    # you no need to put `.db` at back
    file-name: database
  MySQL:
    # Unavailable
    port: 3306
    database: YourDataBase
    username: YourUserName
    password: 1234IsNotAGoodPassword
    host: localhost