## Default Config for ASkyBlock
---
## Game Prefix.
Prefix: "&d[&eASkyBlock&d] &e"
## Max islands homes
# You will have to set this as digit and will be used
# On island!
maxhome: 1
## Allow debugging - Remember this is for Developers only!
debug: false
## Allow to get Updates 
updater: false

## Chat Formattin
chat:
  # Use chat formatting such as &7 will return to ยง7
  UCFormatting: true
  # Team chatting (Just like Facebook)
  teamChat: true

##### Island Related Settings #####
island:
   # Space between islands in blocks - NEVER change this mid-game.
   # Values for a new world:
   # 400 - puts players distance enough that they usually cannot see each other
   # 200 - allows some expansion of the protected zone (recommended)
   # 110 - for compatibility with established worlds. Cozy.
   # 50 - minimum - not recommended
   # IF YOU ARE UPGRADING YOU MUST USE YOUR OLD VALUE EXACTLY, E.G., 110
   # OR RESET YOUR WORLD
   # Value must be an even number
   islandSize: 200
   # Island Hieght
   #   You can use this as island High
   #   Minimum: 20
   islandHieght: 60
   # Default protection range (even number). Min = 0, Recommended = 100
   # Larger values will take longer to calculate the island level
   # For optimal performance, keep protection range at leat 16 blocks less than distance.
   protectionRange: 100
   # Island name limit
   #   Here you can control th
   #   Limit of the island naming size
   #   You can use -1 to make it infinite
   nameLimit: 20
   # Island reset
   #   Here you can control the 
   #   Blocks when players reset their island
   #   NOTE: more higher you made, more lag your server
   #         depends on your schematic blocks
   chunkResetPerBlocks: 256
   # Sea level height (don't changes this mid-game unless you delete the world)
   # Minimum is 0, which means you are playing sky block!
   # If sea level is less than about 10, then players will drop right through it
   # if it exists. Makes for an interesting variation on skyblock.
   seaLevel: 3
   # Restricted commands in Island / SkyBlock
   #   level. You must respect the command format
   #   Such as `/example1, /example2`
   restrictedCommands: "/fly, /sell, /sg"
   # Island reset
   # You can use -1 for unlimited island reset
   reset: 3
   # Island gamemode, you can decide the gamemode
   gamemode: 0
   # Island addMember time out
   #   You can use -1 for unlimited time but 
   #   Recomended 20 seconds
   timeOut: 20
   # Island companion names
   #   Your passion to add this or nor
   #   Syantax: "&aFood?, &eEmergency Food?, &cYour Pet!"
   companionNames: "&aFood?, &eEmergency Food?, &cYour Pet!"
   # Items that will be in the chest when the player starts an island
   # Must be in Nukkit Item format. Format is <ID>:<Qty> or <ID>:<Data>:<Qty>
   # Use <Data> to set the durability of a item or to select sub-items/colors.  
   #
   # Spawn EGGs is not available yet! do not put I warned you :P
   #
   # Check console for errors and guidance after reloading configuration
   chestItems: 'ICE:2 MELON:1 TORCH:2 BONE:1 LAVA_BUCKET:1 PUMPKIN_SEEDS:1 SUGAR_CANE:1 RED_MUSHROOM:1 BROWN_MUSHROOM:1 CACTUS:1 BREAD:1 WHEAT:1 LEATHER_BOOTS:1 LEATHER_HELMET:1 LEATHER_CHESTPLATE:1 LEATHER_LEGGINGS:1'

# This section contains the biomes that can be bought or used
biomesettings:
  # The default cost for changing biome. Can be over-ridden by the Biome settings
  # Default is 100 if this is not set. Cannot be <0.
  defaultcost: 100

  # Default biome - what every player will start with. Default is PLAINS. See below
  # for other options
  defaultbiome: PLAINS
  
# Protection settings
protection:
   # Protection Setting Flags:
   # ACID_DAMAGE, ANVIL, BEACON, BED, BREAK_BLOCKS, BREEDING, BREWING, 
   # BUCKET, COLLECT_LAVA, COLLECT_WATER, CHEST, CHORUS_FRUIT, CRAFTING, CROP_TRAMPLE, 
   # DOOR, EGGS, ENCHANTING, ENDER_PEARL, ENTER_EXIT_MESSAGES, FIRE, FIRE_EXTINGUISH, 
   # FIRE_SPREAD, FURNACE, GATE, HORSE_INVENTORY, HORSE_RIDING, HURT_MOBS, LEASH,
   # LEVER_BUTTON, MOB_SPAWN, PLACE_BLOCKS, PORTAL, PRESSURE_PLATE, PVP,
   # MILKING, NETHER_PVP, REDSTONE, SPAWN_EGGS, SHEARING, VILLAGER_TRADING,
   # VISITOR_ITEM_DROP, VISITOR_ITEM_PICKUP
   #
   # -- World defaults --
   # Applies everywhere and are the default for islands and spawn.
   # If not listed, default is false.
   world:
     # Acid causes damage above sea-level (if acid is active)
     ACID_DAMAGE: true
     # Allow anvil use
     ANVIL: false
     # Allow beacon use
     BEACON: false
     # Allow bed use
     BED: false
     # Players can break blocks or generally damage things
     BREAK_BLOCKS: false
     # Allow animal breeding
     BREEDING: false
     # Allow use of cauldrons and brewing stands
     BREWING: false
     # Allow use of buckets, either fill or dump them
     BUCKET: false
     # Collect Lava (overrides BUCKET setting for collecting lava)
     COLLECT_LAVA: false
     # Collect water (overrides BUCKET setting for collecting water)
     COLLECT_WATER: false
     # Allow access chests of any kind, droppers, dispensers and hoppers
     CHEST: false
     # Allow eating or use of chorus fruit
     CHORUS_FRUIT: false
     # Allow use of crafting benches
     CRAFTING: true
     # Allow creepers to hurt players (but not damage blocks)
     CREEPER_PAIN: true
     # Allow crop trampling
     CROP_TRAMPLE: false
     # Allow use of doors or trapdoors. Not including redstone activations.
     DOOR: true
     # Allow chicken egg throwing
     EGGS: false
     # Allow use of enchanting tables
     ENCHANTING: true
     # Allow enderpearl throwing
     ENDER_PEARL: false
     # Enable or disable join/leave messages from the player's island
     ENTER_EXIT_MESSAGES: true
     # Allow fire (flint & steel use, TNT priming) Making portals is allowed.
     FIRE: false
     # Can extinguish fires by punching them
     FIRE_EXTINGUISH: false
     # Allow fire spreading
     FIRE_SPREAD: false
     # Allow furnace use
     FURNACE: true
     # Allow gate use
     GATE: false
     # Allow horse/llama inventory use - only works when riding is enabled     
     HORSE_INVENTORY: false
     # Allow riding of horses/llamas
     HORSE_RIDING: false
     # Allow friendly mob hurting(cows etc.)
     HURT_MOBS: false
     # Allow monsters hurting
     HURT_MONSTERS: true
     # Allow leash use
     LEASH: false
     # Allow lever or button use
     LEVER_BUTTON: true
     # Cows can be milked
     MILKING: true
     # Animals, etc. can spawn naturally
     MOB_SPAWN: true
     # Allow monsters to spawn naturally
     MONSTER_SPAWN: true
     # Allow PVP in the nether world
     NETHER_PVP: false
     # Players can place blocks
     PLACE_BLOCKS: false
     # Allow portal use
     PORTAL: true
     # Allow pressure plate activation by players
     PRESSURE_PLATE: true
     # Allow PVP in the overworld
     PVP: false
     # Allow adjustment of diodes or comparators
     REDSTONE: false
     # Spawn eggs can be used
     SPAWN_EGGS: false
     # Allow sheep shearing
     SHEARING: false
     # Allow trading with villagers
     VILLAGER_TRADING: true
     # Allow item drop
     VISITOR_ITEM_DROP: true
     # Allow item pickup
     VISITOR_ITEM_PICKUP: true
   # -- Island Settings --
   # Settings for islands. Some are for visitors, some for the island itself.
   # If setting is not listed, it will not show in GUI and the world default will be used.
   # Add settings here to give the player the ability to see them in the GUI. Give the
   # player the permission for the setting for them to be able to change the setting.
   island:
     # Allow visitor anvil use
     ANVIL: true
     # Allow visitor beacon use
     BEACON: false
     # Allow visitor bed use
     BED: false
     # Allow visitor block breaking, or other damage
     BREAK_BLOCKS: false
     # Allow visitor animal breeding
     BREEDING: false
     # Allow visitor use of cauldrons and brewing stands
     BREWING: false
     # Allow visitor access chests of any kind, droppers, dispensers and hoppers
     CHEST: false
     # Allow visitors to use crafting benches
     CRAFTING: true
     # Allow visitor use of doors or trapdoors. Not including redstone activations.
     DOOR: true
     # Allow visitor chicken egg throwing
     EGGS: false
     # Allow visitors to use enchanting tables
     ENCHANTING: true
     # Allow visitor furnace use
     FURNACE: true
     # Allow gate use
     GATE: true
     # Allow portal use by visitors
     PORTAL: true
     # Allow pressure plate activation by visitors (players only)
     PRESSURE_PLATE: false
     # Allow adjustment of diodes or comparators
     REDSTONE: false
     # Allow visitors to shear sheep
     SHEARING: false
   
# General section
general:
  # The time for teleports 
  # Must be in integer
  # Put 0 if you dont want to enable this
  islandTeleportDelay: 2
  # Teleport cancel distance
  # How far players can go to cancel
  # Teleports
  teleportCancelDistance: 0.2
  # Broadcast 1st time challenge completion messages to all players.
  # Change to false if the spam becomes too much.
  broadcastmessages: true
  
## Database
# Recomended to NOT change this in mid game
database:
  # Configuration of DATABASE Connection:
  #  DBLIB  - default connection, defined in DbLib plugin
  #  SQLITE - custom sqlite file
  #  MYSQL  - custom MySql configuration
  connection: sqlite
  SQLite:
    # SQlite file name.
    # You can pick your name and
    # you no need to put `.db` at back
    file-name: database
  MySQL:
    port: 3306
    database: YourDataBase
    username: YourUserName
    password: 1234IsNotAGoodPassword
    host: localhost

schematicsection:
   # All schematics should be put in the schematics folder

   # Schematic panel - if more than one schematic is available to the player
   # Show a panel to choose. If this is false, no panel is shown and the starter 
   # island is picked by permission. If a player has more than one permission
   # the island selected is undefined - the plugin will pick one.
   # Permissions are taken from the below schematics section even if the GUI is
   # not used.
  useschematicspanel: true

   # Random island, only apply when useschematicspanel is false - if set to false
   # the plugin will choose the first island it found with the user permissions
   # to generate a new island. If set to true, the plugin will generate an island
   # randomly from the list of all islands available to the player.
  chooseislandrandomly: false

  # This section lists all the schematics available
  # Settings are:
  # show - whether this island will show in the GUI or not. Typically used for partner
  #        schematics, but can be used to temporarily hide schematics.
  # icon - the icon to show in the GUI. It must be a known Material
  # order - the priority for showing in the GUI. Lower numbers are shown first.
  # name - a friendly short name for the schematic. Color codes okay.
  # description - a longer description. Use | to split lines. Color codes okay.
  # filename - the filename of the schematic in the schematic folder
  # useDefaultChest - fill a chest on the island with the items in this config. If false
  #                   the contents will come from the schematic.
  # partnerSchematic - the island that will be pasted in the Nether.
  # biome - the biome this island should have. All pasted blocks will have this biome.
  # These next settings may cause lag if true. Default is false. Use judiciously.
  # pasteentities - if the schematic has entities in it (mobs) this will paste them.
  # usephysics - if true, causes lava or water to flow after being pasted.
  # pasteair - Only set to true if you need to paste below sea level.
  # permission - the permission required to use this schematic. It can be anything you like
  # You can add or remove from this list. If this section is missing, only the default
  # island works.
  schematics:
    # default heading is required
    default:
      # Icon - if this is missing or wrong, it will be a MAP
      icon: DIRT
      # Order of preference in listing
      order: 1
      # Short name - color codes with & okay
      name: "The Original"
      # Longer description. Use | for new lines. Color codes okay.
      description: "Challenging|starter|island!"
      # Filename of the schematic in the schematic folder
      filename: island.schematic
      # Use default chest if true, or use schematic chest contents if false
      useDefaultChest: true
      # Which schematic will be used in the opposite world if newnether:true
      # If there is no partner, this island will be used
      partnerSchematic: nether
      #Level handicap zeros the initial island level. 
      levelHandicap: 3

    # This is the default nether island - do not remove this section!
    nether:
      # Hide or show this schematic to players in the GUI
      show: false
      icon: NETHERRACK
      # If the biome is HELL it is assumed this island goes in the Nether
      biome: HELL
      name: "NetherBlock Island"
      description: "An island in the nether|overlooked by a mob tower"
      filename: nether.schematic
      # Nether schematics should generally use the schematic chest contents
      useDefaultChest: false
      # The partner to this schematic is the default island
      partnerSchematic: default
      # Schematics can include entities (mobs) in them and if pasteentities is true,
      # mobs will be pasted. 
      pasteentities: true
      # Usephysics causes lava or water to flow after being pasted. Change to false
      # if it lags
      usephysics: true
      #Level handicap zeros the initial island level. 
      levelHandicap: 93
  
    # Additional heading names can be anything you like, but must be unique
    island1:
      # Credit to Antal1609 for this schematic!
      icon: RED_ROSE
      order: 2
      name: "Island Duo"
      description: "Two close islands!|Double the fun,|but a little easier.|&a[Credit] Antal1609"
      filename: double.schematic
      # Schematics can have biomes set when they are created
      biome: FOREST
      # If useDefaultChest is false, the items in the schematic will be used
      # If false, the default chest items will be used, or the list below
      useDefaultChest: true
      # Chest items defined here will override the default chest items.
      # You can set the chest items here in this list
      # Material:Qty, or Material:Data:Qty
      #chestItems:
      #- MELON:1
      #- ICE:1
      # Your island companion. Overrides the default setting. If more than one is
      # listed, one will be chosen at random.
      # Options are: COW, PIG, SHEEP, CHICKEN, VILLAGER, HORSE, IRON_GOLEM, OCELOT,
      # RABBIT, WOLF or NOTHING. Default is COW.
      companion:
      - CHICKEN 
      # This is a list of names, picked at random that will apply to the companion
      # You can add more if you like. If none are listed, the companion will not be
      # named.
      companionnames:
      - "&9[player]'s chicken"
      - "&dFree-Range Eggs"
      partnerSchematic: nether
      #permission: any.perm.you.like
      #Level handicap zeros the initial island level. 
      levelHandicap: 9

    # New snowy schematic
    extrahard:
      icon: OBSIDIAN
      order: 3
      # Ski theme - a black diamond run is hard.
      name: "&lBlack &bDiamonds"
      description: "Experts only!|&aMinimal resources|&awith a few diamonds."
      filename: harder.schematic
      biome: COLD_BEACH
      useDefaultChest: false
      # Chest items defined here will override the default chest items.
      # You can set the chest items here in this list
      # Material:Qty, or Material:Data:Qty
      #chestItems:
      #- MELON:1
      #- ICE:1
      # Schematics that require water or lava to hover can prevent physics when pasting
      usephysics: false
      # Schematics may include entities (mobs) in them and if pasteentities is true,
      # mobs will be pasted.
      # Example: Setting this to true for this schematic will give a wolf.
      pasteentities: false
      partnerSchematic: nether
      #permission: any.perm.you.like
      # This optional block determines where the player will spawn. It must be unique in
      # the schematic and will be replaced by air when pasted.
      #spawnblock: SPONGE
      #Level handicap zeros the initial island level. 
      levelHandicap: 1